# Generated by Django 4.2.3 on 2023-08-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webschool', '0003_rename_students_profile_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='date_creation',
            new_name='lesson_date',
        ),
    ]
