# Generated by Django 4.2.3 on 2023-08-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webschool', '0004_rename_date_creation_lesson_lesson_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='lesson',
            name='grade_for',
            field=models.ManyToManyField(to='webschool.grade'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_in',
            field=models.ManyToManyField(to='webschool.grade'),
        ),
    ]
