# Generated by Django 4.2.3 on 2023-08-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webschool', '0005_grade_remove_student_grade_lesson_grade_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profile_photo',
        ),
    ]
