# Generated by Django 4.2.3 on 2023-08-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webschool', '0009_lesson_l_or_r_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='l_or_r_tag',
        ),
        migrations.AddField(
            model_name='lesson',
            name='l_or_r_tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='webschool.tag'),
        ),
    ]
