# Generated by Django 4.2.3 on 2023-08-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webschool', '0011_alter_lesson_l_or_r_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='l_or_r_tag',
        ),
    ]
