# Generated by Django 4.2.3 on 2023-08-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webschool', '0013_alter_lesson_lesson_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lesson',
        ),
    ]
