# Generated by Django 4.2.3 on 2023-08-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webschool', '0015_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='notes_pdf/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webschool.teacher')),
                ('grade_for', models.ManyToManyField(to='webschool.grade')),
            ],
        ),
    ]
